export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  ACCOUNT: '/account',
  ACCOUNT_ADDRESSES: '/account/addresses',
  CART: '/cart',
  COLLECTIONS: {
    ALL: '/collections/all',
    LATEST: '/collections/latest',
    PANTS: '/collections/pants',
    TEES: '/collections/tees',
    SHORTS: '/collections/shorts',
  },
  COLLECTION_FUNCTION: (tag: string) => `/collections/${tag}`,
  PRODUCT_DETAILS: (id: string | number) => `/product-details/${id}`,
  SEARCH: '/search',
  BUY_IT_NOW: (id: string | number, size: string) => `/buy-it-now/${id}/${size}`,
  CHECKOUT: '/checkout',
  ORDER_CONFIRMATION: (id: string | number) => `/order-confirmation?orderId=${id}`,
  DASHBOARD: {
    // MAIN: '/dashboard',
    MAIN: '/dashboard/orders',
    ORDERS: '/dashboard/orders',
    ORDER_DETAILS: (id: string | number) => `/dashboard/orders/order-details/${id}`,
    PRODUCTS: '/dashboard/products',
    ANALYTICS: '/dashboard/analytics',
    CUSTOMERS: '/dashboard/customers',
    DISCOUNTS: '/dashboard/discounts',
    THEMES: '/dashboard/themes',
  },
}